Basic.class			:	Basic.java Lexer.java Parser.java Interpreter.java
						javac Basic.java
			
CollatzConjecture	:	Basic.class
						java Basic CollatzConjecture.txt

ClassAverage		:	Basic.class
						java Basic ClassAverage.txt

FizzBuzz			:	Basic.class
						java Basic FizzBuzz.txt
				
clean				:
						rm *.class
						rm ASTNodes/*.class